import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  collectionCardContainer: {
    width: '100%',
    marginVertical: '2%',
  },
  editButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingHorizontal: '3%',
    borderRadius: 10,
    position: 'absolute',
    top: 10,
    right: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 5,
  },
  iconStyle: {
    height: 22,
    width: 22,
    borderRadius: 11,
    marginRight: '3%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0)',
    paddingHorizontal: '1%',
    paddingVertical: '4%',
  },
  imageStyle: {
    width: '100%',
    height: 400,
  },
  collectionInfoContainer: {
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    position: 'absolute',
    bottom: 10,
    paddingHorizontal: '4%',
  },
  collectionNameText: {
    fontSize: 22,
    color: 'white',
    fontWeight: '500',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowRadius: 1,
    textShadowOffset: {width: 1, height: 1.2},
    fontFamily: 'Roboto-Bold',
  },
  productsCountText: {
    fontSize: 14,
    color: 'white',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowRadius: 0.1,
    textShadowOffset: {width: 1, height: 1},
    fontFamily: 'Roboto-Bold',
  },
  copyLinkButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    paddingHorizontal: '3%',
    paddingVertical: '2%',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 5,
  },
  copyLinkText: {
    color: 'white',
  },
});
