import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  couponOverviewContainer: {
    width: '90%',
    borderRadius: 10,
    minHeight: '40%',
    zIndex: 2,
    backgroundColor: 'white',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 5,
  },
  couponInfoContainer: {
    borderBottomWidth: 2,
    borderColor: 'rgba(0,0,0,0.5)',
    borderStyle: 'dashed',
  },
  couponValidityText: {
    width: '100%',
    backgroundColor: '#00a362',
    textAlign: 'center',
    color: 'white',
    fontSize: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    paddingVertical: '1%',
  },
  couponNameText: {
    textAlign: 'center',
    marginTop: '4%',
    marginBottom: '1%',
    fontSize: 22,
    color: 'black',
  },
  couponCodeText: {
    textAlign: 'center',
    fontSize: 24,
    color: 'black',
    marginVertical: '2%',
  },
  copyCodeButton: {
    flexDirection: 'row',
    backgroundColor: 'black',
    alignSelf: 'center',
    width: '90%',
    borderRadius: 5,
    paddingVertical: '2%',
    justifyContent: 'center',
    marginVertical: '2%',
  },
  copyCodeText: {
    textAlign: 'center',
    alignSelf: 'center',
    color: 'white',
  },
  codeEndDateText: {
    marginTop: '2%',
    marginBottom: '10%',
    alignSelf: 'center',
  },
});
