import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('screen');

export const styles = StyleSheet.create({
  productsTabContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  modalActiveBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    elevation: 4,
    right: 0,
    zIndex: 5,
  },
  headerStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 60,
    justifyContent: 'center',
    backgroundColor: 'black',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.2)',
  },
  headingText: {
    alignSelf: 'center',
    fontSize: 22,
    color: 'white',
    fontFamily: 'Roboto-Bold',
  },
  headerButtonPosition: {
    position: 'absolute',
    right: 5,
    alignContent: 'flex-end',
  },
  switchTabContainer: {
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 10,
    backgroundColor: 'white',
  },
  switchTabContainerStyle: {
    width: '90%',
    height: 35,
    borderRadius: 5,
    marginTop: '2%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignSelf: 'center',
    marginBottom: '3%',
    position: 'relative',
  },
  switchTabStyle: {
    width: '50%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  thumbnailModalBackdrop: {
    flex: 1,
  },
  thumbnailModalContainer: {
    backgroundColor: 'white',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '35%',
    paddingHorizontal: '4%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  thumbnailModalHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '5%',
    marginVertical: '5%',
  },
  thumbnailModalHeaderText: {
    color: 'black',
    fontSize: 20,
    fontWeight: '600',
  },
  thumbnailModalHeaderCross: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 24,
    height: 24,
    borderRadius: 12,
    borderColor: 'rgba(0,0,0,0.8)',
    borderWidth: 2,
  },
  thumbnailModalContentContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: '10%',
  },
  cameraOptionContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraOptionText: {
    color: 'black',
  },
  galleryOptionContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  galleryOptionText: {
    color: 'black',
  },
  thumbnailErrorMessageContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  newCollectionModalBackdrop: {
    flex: 1,
  },
  newCollectionModalContainer: {
    backgroundColor: 'white',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '50%',
    paddingHorizontal: '4%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  newCollectionModalHeading: {
    textAlign: 'center',
    color: 'black',
    fontSize: 20,
    fontWeight: '700',
    marginVertical: '4%',
  },
  newCollectionModalLabel: {
    marginVertical: '2%',
    fontSize: 16,
    color: 'black',
    fontWeight: '500',
  },
  newCollectionNameInput: {
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    paddingHorizontal: '5%',
    backgroundColor: 'white',
    height: 50,
  },
  newCollectionThumbnailUploadContainer: {
    width: '100%',
    borderWidth: 1,
    height: 50,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    paddingHorizontal: '1%',
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
  },
  newCollectionThumbnailUploadButton: {
    height: '80%',
    backgroundColor: 'black',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    paddingHorizontal: '5%',
  },
  newCollectionThumbnailUploadText: {
    color: 'white',
  },
  newCollectionConfirmButton: {
    width: '100%',
    backgroundColor: 'black',
    borderRadius: 4,
    height: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: '5%',
    paddingHorizontal: '5%',
  },
  confirmButtonIcon: {
    height: 30,
    width: 30,
    borderRadius: 15,
    marginRight: '2%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  confirmButtonText: {
    color: 'white',
  },
  newCollectionCancelText: {
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontWeight: '600',
  },
  footerComponentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: '3%',
  },
  errorMessageContainer: {
    alignSelf: 'center',
    marginBottom: 2,
  },
  errorMessageText: {
    fontSize: 12,
    color: 'red',
  },
});
