import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('screen');

export const styles = StyleSheet.create({
  createCouponScreenContainer: {
    flex: 1,
  },
  createCouponContainer: {
    flex: 1,
    paddingBottom: '15%',
  },
  brandsModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  brandsModalContentContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    paddingHorizontal: '5%',
  },
  brandsModalHeaderText: {
    marginVertical: '5%',
    textAlign: 'center',
    fontSize: 20,
    color: 'black',
  },
  brandsModalConfirmButton: {
    alignSelf: 'center',
    backgroundColor: 'black',
    width: '30%',
    marginVertical: '4%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: '2%',
  },
  brandsModalConfirmButtonText: {
    color: 'white',
    fontSize: 16,
  },
  storesModalContainer: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  storesModalHeaderText: {
    marginVertical: '5%',
    textAlign: 'center',
    fontSize: 20,
    color: 'black',
  },
  storesModalContentContainer: {
    flex: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
    borderTopWidth: 1,
  },
  storesModalConfirmButton: {
    alignSelf: 'center',
    backgroundColor: 'black',
    width: '30%',
    marginVertical: '4%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: '2%',
  },
  storesModalConfirmButtonText: {
    color: 'white',
    fontSize: 16,
  },
  createCouponContentContainer: {
    flex: 1,
    paddingHorizontal: '5%',
  },
  couponDetailsHeaderText: {
    textAlign: 'center',
    fontSize: 18,
    color: 'black',
    marginTop: '4%',
  },
  createCouponLabelText: {
    marginVertical: '5%',
    fontSize: 15,
    color: 'black',
    fontWeight: '500',
  },
  selectedConfirmedContainer: {
    flexDirection: 'row',
    marginTop: '5%',
  },
  selectedConfirmedText: {
    color: 'black',
    marginLeft: '3%',
  },
  minimumOrderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  minimumOrderSectionContainer: {
    width: '45%',
  },
  selectBrandsContainer: {
    flex: 1,
  },
  selectBrandsBox: {
    marginVertical: '5%',
    width: '100%',
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    paddingHorizontal: '3%',
    backgroundColor: 'white',
  },
  selectBrandsText: {
    color: 'gray',
  },
  selectBrandsButton: {
    height: '80%',
    width: '25%',
    borderRadius: 4,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectBrandsButtonText: {
    color: 'white',
    fontSize: 12,
  },
  selectProductsContainer: {
    flex: 1,
  },
  selectProductsBox: {
    marginVertical: '5%',
    width: '100%',
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    paddingHorizontal: '3%',
    backgroundColor: 'white',
  },
  selectProductsText: {
    color: 'gray',
  },
  selectProductsButton: {
    height: '80%',
    width: '25%',
    borderRadius: 4,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectProductsButtonText: {
    color: 'white',
    fontSize: 12,
  },
  selectDatesContainer: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    paddingHorizontal: '5%',
    backgroundColor: 'white',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '5%',
    fontSize: 15,
    color: 'black',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: '500',
  },
  selectDatesSectionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  selectDatesSubsectionContainer: {
    width: '45%',
  },
  selectDatesSubsectionText: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    backgroundColor: 'white',
    paddingHorizontal: '5%',
    marginVertical: '5%',
    fontSize: 14,
    color: 'black',
    textAlign: 'center',
    fontWeight: '500',
  },
  selectedDateSubsectionText: {
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    color: 'gray',
    textAlign: 'center',
    backgroundColor: 'white',
    paddingHorizontal: '5%',
  },
  selectStoresBox: {
    marginTop: '5%',
    width: '100%',
    height: 40,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.3)',
    borderRadius: 4,
    alignItems: 'center',
    backgroundColor: 'white',
    paddingHorizontal: '3%',
    flexDirection: 'row',
  },
  selectStoresText: {
    color: 'gray',
  },
  selectStoresButton: {
    height: '80%',
    width: '25%',
    borderRadius: 4,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectStoresButtonText: {
    color: 'white',
    fontSize: 12,
  },
  couponNamingHeaderText: {
    textAlign: 'center',
    fontSize: 18,
    color: 'black',
    marginTop: '10%',
  },
  errorMessageContainer: {
    marginTop: '1%',
  },
  errorMessageText: {
    fontSize: 12,
    color: 'red',
  },
  button: {
    height: 40,
    borderRadius: 5,
    width: '30%',
    alignSelf: 'center',
    marginVertical: '5%',
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputStyle: {
    width: '100%',
    color: 'black',
    borderBottomWidth: 1,
    borderColor: 'black',
    paddingVertical: '3%',
    marginBottom: 15,
  },
});
